### ISSUE TITLE
Illegal typecast: float to <16 x float>

### ISSUE THREAD

**Issue by shirishr** [plaidml/plaidvision#15]
plaidbench --batch-size 16 keras --train mobilenet runs into an error:

Illegal typecast: float to <16 x float>
Set --print-stacktraces to see the entire traceback

**Comment by brianretford** [comment]
Hey, can you list which version of plaidml you're using, which platform, and what hardware you have? It seems like our hardware config is trying to use a vector size of 16 and your opencl stack doesn't understand it.

**Comment by shirishr** [comment]
plaidml: 0.3.5
ubuntu 18.04
ocl-icd-opencl-dev    2.2.11-1ubuntu1 
cpu only
originally a windows machine. Dell Inspiron 15R with intel i7

**Comment by brianretford** [comment]
Hmmm, which opencl drivers are you using? Using Intel's NEO or their older OpenCL drivers PlaidML tends to work. Could you install clinfo and provide a dump of that? I would expect plaidml-setup to offer both GPU and CPU optionsl.

I would say our CPU perf leaves something to be desired and you're probably better off using anything native or mkl-dnn based. That said, I imagine you must have some kind of GPU? It looks like that laptop has a haswell in it and an hd4400. In theory the hd4400 is twice as fast as the CPU.

**Comment by shirishr** [comment]
@brianretford 
I am closing this now since clinfo shows platforms = 0. 
I am not ready to experiment with drivers at this point.
Thanks
